### ISSUE TITLE
"echo" no longer works with 0.20

### ISSUE THREAD

**Issue by lscrd** [mratsim/Arraymancer#364]
The following program fails to compile with 0.20 and with the development version:

```
import arraymancer
echo [1.0, 2.0].toTensor
```

It seems to be a known issue (see #348 and #355) and it is supposed to have been solved. But, for me, with the current versions, it is still present.

I use stable and development versions built with "choosenim" on a Linux Manjaro.

**Comment by mratsim** [comment]
I guess you are using the latest stable version of Arraymancer, devel works.

I will release a new stable version with https://github.com/mratsim/Arraymancer/pull/349 included.

**Comment by lscrd** [comment]
Thanks for your answer.

Unfortunately, for me, it doesn’t work with the development version and I get exactly the same error message. In case there was something wrong in my installation, I uninstalled both versions and reinstalled them with no success.

Have you any idea what would cause this different behavior?

**Comment by mratsim** [comment]
I've released a new stable version: https://github.com/mratsim/Arraymancer/releases/tag/v0.5.1, hopefully it should work with 0.20.0, 0.20.2 and devel.

Do you still have the issue?

**Comment by lscrd** [comment]
Good news: the program compiles, so the issue seems to be solved.
Bad news: the program doesn’t link. I get an error: Undefined reference to "NIM_UNLIKELY".

Also, in "arraymancer.nimble" the version number is still 0.5.0 instead of 0.5.1, so installation with nimble overwrites the previous 0.5.0 release.

**Comment by mratsim** [comment]
good catch, I've bumped the versions to v0.5.2.

Regarding NIM_UNLIKELY, it should be defined in nimbase.h

see: https://github.com/nim-lang/Nim/blob/v0.20.2/lib/nimbase.h#L444-L455.

That's very strange.

**Comment by lscrd** [comment]
Thanks for the information. It helped me to find the problem. In the cache directory, I once made a copy of "nimbase.h" in a cache directory and this was this old version which was used.

So, forget it. It was my mistake. Thanks for this new version.
